- type: job
  id: TsfForecon
  name: job-name-tsf-forecon
  description: job-description-tsf-forecon
  playTimeTracker: JobTsfForecon
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 108000 # 65 hours
    - !type:RoleTimeRequirement
      role: JobPirate
      time: 3600 # 1 hour
    - !type:DepartmentTimeRequirement
      department: Security
      time: 36000 # 10 hours This doesn't actually matter it's just here because the spasaka also has hour lock
  startingGear: TSFMCForeconStandard
  icon: JobIconTSFForecon
  supervisors: job-supervisors-sheriff
  weight: 0
  displayWeight: 46
  assignedCompany: TSF
  canBeAntag: false
  setPreference: true
  accessGroups:
  - AllAccess
  access:
  - TsfmcEngineering
  special:
  - !type:AddComponentSpecial
    components:
    - type: NpcFactionMember
      factions:
      - TSFMC
    - type: ChatRank
      rank: tsf-forecon
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant, TrackingImplant ]
  - !type:AddLanguageSpecial
    languagesSpoken:
    - SolCommon
    languagesUnderstood:
    - SolCommon

- type: startingGear
  id: TSFMCForeconStandard
  equipment:
    jumpsuit: ClothingUniformTsfmcMopp
    back: ClothingBackpackERTLeader
    eyes: ClothingEyesHudNfsd
    ears: ClothingHeadsetAltTsfmcMarsoc
    gloves: ClothingHandsGlovesTacticalCombatBlack
    outerClothing: ClothingOuterHardsuitM86Mk4
    shoes: ClothingShoesBootsMagAdv
    id: MarsocPDA
    pocket1: CrowbarPocket
    pocket2: RadioHandheldNF
    belt: ClothingBeltWebbingsNormalTSFMC
    neck: ClothingNeckIFFCyan
  inhand:
  - UndeterminedTSFForeconKit
